#prod

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.web.resources.static-locations=file:/uploads/,classpath:/static/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
